mod:
  sys_account:
    enabled: true
  sys_analyser:
    plot: false
    echart_plot: true
    enabled: true
  sys_progress:
    enabled: true
  sys_risk:
    enabled: true
  sys_run:
    enabled: true
  sys_log:
    enabled: true
